#!/usr/bin/env bash
# Re-runnable connectivity smoke test — two independent backend services.
# Generated by api-connectivity-agent. Do not commit credentials (none needed here).
# Usage: bash generated-docs/specs/api-smoke-test.sh
#
# Services:
#   1. auth-api / BFF      http://localhost:4424
#   2. transactions-api    http://localhost:4423/transactions-api
#
# Auth: both services authenticate via a browser-managed, HttpOnly,
# Secure, SameSite=Strict session cookie minted by POST /v1/auth/login
# on the BFF (SessionCookie scheme, apiKey-in-cookie, name "session").
# There is no static token/key the frontend holds, so this script never
# logs in and never sends a session cookie — it only proves each service
# process is up and responding correctly.
#
# REACHABILITY-ONLY RULE (see .claude/policies/authentication-intake.md
# Rule 10): because service 2 requires that session cookie on every
# route and we deliberately probe it WITHOUT one, an unauthenticated
# 401 (or 403) is the CORRECT, expected response — it proves the
# service is up and correctly enforcing auth. This script therefore
# scores 401/403 on service 2 as a PASS (exit 0), not a failure.
# A connection error, 404 (wrong URL / not mounted), or 5xx (server
# error) is a real FAILURE regardless of this rule.
#
# Service 1's /v1/health requires no auth at all (security: [] in the
# spec) and must return 2xx to pass — 401/403 there would itself be a
# problem (the health probe should never be auth-gated).
#
# /api-status --check and /api-go-live re-run this script and rely on
# its exit code (0 = both services reachable, 1 = at least one is not).

set -u

FAIL_COUNT=0

# probe LABEL URL "space-separated list of HTTP status codes that PASS"
probe() {
  local label="$1" url="$2" pass_codes="$3"
  local body_file="/tmp/smoke-body-$$-$(echo "$label" | tr -c 'A-Za-z0-9' '_')"
  local http_code
  http_code="$(curl -sS -o "$body_file" -w '%{http_code}' "$url")"
  local curl_exit=$?
  rm -f "$body_file"

  if [ "$curl_exit" -ne 0 ]; then
    echo "FAIL  $label -> curl error (exit $curl_exit: connection refused / DNS failure / timeout)"
    FAIL_COUNT=$((FAIL_COUNT + 1))
    return
  fi

  local ok
  for ok in $pass_codes; do
    if [ "$http_code" = "$ok" ]; then
      echo "PASS  $label -> HTTP $http_code"
      return
    fi
  done

  echo "FAIL  $label -> HTTP $http_code (expected one of: $pass_codes)"
  FAIL_COUNT=$((FAIL_COUNT + 1))
}

echo "== Service 1: auth-api / BFF health probe (must be 2xx — no auth required) =="
probe "auth-api /v1/health" "http://localhost:4424/v1/health" "200 201 202 203 204"

echo
echo "== Service 2: transactions-api reachability probe (2xx OR 401/403 = PASS; see reachability-only rule above) =="
probe "transactions-api /v1/file-sources" "http://localhost:4423/transactions-api/v1/file-sources" "200 201 202 203 204 401 403"

echo
if [ "$FAIL_COUNT" -eq 0 ]; then
  echo "RESULT: PASS — both services reachable"
  exit 0
else
  echo "RESULT: FAIL — $FAIL_COUNT of 2 service(s) unreachable"
  exit 1
fi
